yoga changes

diff --git a/commands/sn b/commands/sn
--- a/commands/sn
+++ b/commands/sn
@@ -8,6 +8,6 @@ img=$(mktemp '/tmp/img-XXXXXX.png')
 scrot -s -z "$@" $img >/dev/null 2>&1 || exit
 res=$(curl -sH "Authorization: Client-ID $clientid" -F "image=@$img" "https://api.imgur.com/3/upload")
 
-echo $res | grep -qo '"status":200' && link=$(echo $res | sed -e 's/.*"link":"\([^"]*\).*/\1/' -e 's/\\//g')
-test -n "$link" && (printf $link | xclip; printf "\a" && rm "$img") || echo "$res" > "$img.error"
-echo $link
+# echo $res | grep -qo '"status":200' && link=$(echo $res | sed -e 's/.*"link":"\([^"]*\).*/\1/' -e 's/\\//g')
+# test -n "$link" && (printf $link | xclip; printf "\a" && rm "$img") || echo "$res" > "$img.error"
+# echo $link
